### ISSUE TITLE
Add Favicon To The Website(Feature Request) 

### ISSUE THREAD

**Issue by bhaveshgoyal182** [CodeTrophs/FaceID#1465]
The current website, does not have any default Favicon. I can add this, if you'll assign this issue to me.

**Comment by aryasoni98** [comment]
Okay , Sure

**Comment by niksseif** [comment]
I can add the Favicon if this issue is still open

**Comment by bhaveshgoyal182** [comment]
@niksseif I have already made PR #1558 !
