### ISSUE TITLE
Implementation lazy load images with Lazysize

### ISSUE THREAD

**Issue by wisnuwiry** [CodeTrophs/FaceID#1498]
## Description

Add new feature lazy load images, and add default placeholder images, when images can't loaded.

**Comment by Raj-Banerjee** [comment]
What is the issue here? can you explain?

**Comment by CodingCarter** [comment]
> What is the issue here? can you explain?

The script makes it so that images are not loaded until they are scrolled into view; therefore, performance is vastly increased.
