### ISSUE TITLE
Please add your repo to this hacktoberfest by using its tag

### ISSUE THREAD

**Issue by ishgary** [CodeTrophs/FaceID#1623]
Please add your repo to this hacktoberfest by using its tag

**Comment by aryasoni98** [comment]
I don't understand your point . @ishgary

**Comment by SantiagoMachado** [comment]
in the hacktober page appear this legend related to this repo / PR status

"Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR."

**Comment by SantiagoMachado** [comment]
![image](https://user-images.githubusercontent.com/68918270/95113795-5d8c8880-0719-11eb-85ee-2a74aa341b62.png)

**Comment by ianmustafa** [comment]
@ishgary @SantiagoMachado please read #302
