### ISSUE TITLE
Can`t make Pull request what is the problem 

### ISSUE THREAD

**Issue by mik3bg** [CodeTrophs/FaceID#1905]
@github-actions
CI / build (pull_request) Successful in 4s
Details
@netlify
Header rules Failing after 19s — Deploy failed
Details
@netlify
Mixed content Failing after 20s — Deploy failed
Details
@netlify
Pages changed Failing after 19s — Deploy failed
Details
@netlify
Redirect rules Failing after 20s — Deploy failed
Details
@netlify
deploy/netlify — Deploy preview failed. 
This checks failed after I make pull request what is the issue.

**Comment by namanjain007** [comment]
https://stackoverflow.com/questions/58654530/how-to-reject-a-pull-request-if-tests-are-failed-github-actions
