### ISSUE TITLE
PR not avaiable

### ISSUE THREAD

**Issue by DianaRodarte** [CodeTrophs/FaceID#1987]
Hello! I wanted to contribute to this! May I have permission to submit a pull request?

**Comment by JaredStrandWSU** [comment]
Me too!

**Comment by vipulsnp** [comment]
@DianaRodarte Everyone can submit a PR to the repo.

**Comment by camiladev** [comment]
Hello, I did the pull but on the hacktoberfest page this is invalid.

**Comment by vipulsnp** [comment]
This repository is not valid towards contributions for hacktoberfest. Check #302
