### ISSUE TITLE
Why nobody is accepting pull requests

### ISSUE THREAD

**Issue by RaoHammas** [CodeTrophs/FaceID#2033]
Yesterday there were **1.3K** pull requests and today there are **1.4K** , Why nobody is accepting pull requests and merging ?

**Comment by aryasoni98** [comment]
Because we'r create automatic merge pull requests script workflow @RaoHammas

**Comment by RaoHammas** [comment]
@aryasoni98 ahan ! Ok got it. hope it is done soon. Good luck :)

**Comment by aryasoni98** [comment]
Yes , Thanku @RaoHammas
