### ISSUE TITLE
No of PR

### ISSUE THREAD

**Issue by devkapilbansal** [CodeTrophs/FaceID#256]
As far as I know, no. of PR required for hacktoberfest is 4
Also, can we make PR now or in October only on this repo.

**Comment by krishshah920** [comment]
PR counts starts from 1st of october

**Comment by devkapilbansal** [comment]
> PR counts starts from 1st of october

How many Pr we need to make on this repository

**Comment by krishshah920** [comment]
One

**Comment by devkapilbansal** [comment]
I made my first pr. Am I eligible for tee as mentioned in about section?
