### ISSUE TITLE
Hacktoberfest Values

### ISSUE THREAD

**Issue by IamMayankThakur** [CodeTrophs/FaceID#271]
This repo goes against the hacktoberfest values.
Repos like this, where people just have to add their name in a file just to get a "+1" in their PR count are discouraged by hacktoberfest.

Strongly encourage everyone to use hacktoberfest for learning and not for a free T-shirt by using unethical means.

https://hacktoberfest.digitalocean.com/details#quality

**Comment by favre49** [comment]
[It should count as spam](https://hacktoberfest.digitalocean.com/details#spam). Regardless, this is pretty sad.

**Comment by aindrila2412** [comment]
Indeed, and this repository is not eligible for Hacktoberfest 2020. Such a waste of time and energy.

**Comment by LeoMajorR** [comment]
Yes, it's against Core Values of what Hacktober Fest aims and should be discouraged. People really work hard for this.

**Comment by amenat** [comment]
You can report it here: https://hacktoberfest.digitalocean.com/report
