### ISSUE TITLE
Please merge the opened pull requests

### ISSUE THREAD

**Issue by Anishahaha** [CodeTrophs/FaceID#2775]
@irshadjsr21

**Comment by shubham1172** [comment]
Check this out #302

**Comment by Anishahaha** [comment]
> Check this out #302

@shubham1172 can you tag the repositories where I can contribute for hacktoberfest 2020?

**Comment by shubham1172** [comment]
The same issue suggests this place to find out repositories for contribution - https://hacktoberfest.digitalocean.com/#projects
