### ISSUE TITLE
I want to contribute in this repo

### ISSUE THREAD

**Issue by davedevelopers** [CodeTrophs/FaceID#534]

**Comment by aryasoni98** [comment]
Yes sure @davedevelopers

**Comment by KasunHewagama** [comment]
Even for beginners, they mentioned some path to go through and contribute

**Comment by geeks5551** [comment]
can I contribute to this issue? looking interesting ? can you please assign me with  this issue?

**Comment by aryasoni98** [comment]
Yes , Sure @geeks5551
