### ISSUE TITLE
Checks Failing

### ISSUE THREAD

**Issue by deepakshisud** [CodeTrophs/FaceID#846]
I have tried to create a pull request 5 times and the checks fail. 
At first, I couldn't figure out the problem but then I looked at the deploy details and found that many contributors have the wrong format for their .md files while there is no error in my file. Therefore, the checks fail every time. One person cannot go through the entire participant folder. Please do something about it.

**Comment by wilds** [comment]
#975 this may fix the issue

**Comment by Dishebh** [comment]
Merged, @wilds
